model and miratyon
mavidurak/orientation-api pull request #11
Opened 2021-06-22 14:19 UTC by burakack

2021-06-25 19:52 UTC, saracalihan requested changes

2021-06-25 19:52 UTC, saracalihan commented on migrations/20210606170510-create-wanted_contents.js
> +          allowNull: true,
`defaultValue` eklenmeli

2021-06-25 19:52 UTC, saracalihan commented on src/models/users.js
> +      as: 'user_wanted_contents2',
dücgün isimlendirme yapılmalı

2021-06-25 19:52 UTC, saracalihan commented on src/models/wanted_contents.js
> +import { DataTypes } from 'sequelize';
Bu dosyanın ismi **camelCase** olmalı

2021-06-25 19:52 UTC, saracalihan commented on src/models/wanted_contents.js
> +},
Tüm sayfaları girintile

2021-06-25 19:52 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +import wanted_contents from '../../models/wanted_contents';
`models` içine zaten `wanted_contents`'i tutuyoruz bir daha import etmene gerek yok

2021-06-25 19:52 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +        status: Joi.string(),
`status` kullanıcıdan kesinlikle alınmalı

2021-06-25 19:52 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +            content_id:content_id
burası sadece istek listesine eklenmiş 1 tane içeriği getirir.İstek atan user'a ait tüm `wanted_content`'ler getirilmeli

2021-06-25 19:52 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +        if(wanted_content.content_id==content_id)
BUrası zaten yukarıda `content_id`'ye göre veritabanından okuma yaptığın için koşul her zaman true olur

2021-06-25 19:52 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +        router.post('', addnewwantedcontent);
Fonksiyon isimleri `create`, `read`, `update`, `delete` şeklinde olabilir

2021-06-28 08:52 UTC, saracalihan requested changes
`update` ve `delete` işlemleri eklenmeli

2021-06-28 08:52 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +      user_id: req.user_id,
Bu kod çalışmayacak.`req` içine `user_id` diye bir şey tutmuyoruz. `req.user_id` => `req.user.id`

2021-06-29 02:10 UTC, burakack commented on src/routes/wanted_contents/index.js
> +      user_id: req.user_id,
düzeltildi

2021-06-29 09:20 UTC, saracalihan requested changes

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +import Joi from '../../joi';
Bulunduğumuz dosyanın ismi **camelCase** olmalı **snake_case** değil

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +      contentid: req.params,
isimlendirme([CONTRIBUTING.md](https://github.com/mavidurak/orientation-api/blob/main/CONTRIBUTING.md)) dokümanına göre isim vermelisin

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +      contentid: req.params,
`req.params` bir obje, number tipli bir alana obje ile giriş yapamazsın.`req.params` içinden `id`'yi almalısın.

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +  if (wantedContent.user_id === req.user.id) {
Bu user id sorgulamasını yukarıda modeli getirirken( `findOne()` içinde ) yapmak çok daha hızlı ve okunaklı olacaktır.

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +  } else {
Aynı hatayı zaten yukarıda kullanıcıya gönderiyoruz.Sen bizim fazla istihbarat vermemek için `or` kelimesini kullandığımız hata mesajını `or` yokmuş gibi iki parçaya bölmüşsün(`user not found`, `you dont have a permission`).Bu mantıksal yapıyı tek if içinde kontrol etmelisin

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +  const { content_id } = req.params;
`params`  içinde `content_id` denilem bir alan yok `contentId` var.(Dosya sonundaki router'da böyle yazmışsın)

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +  const { user_id } = req.user.id;
`req.user.id` içinde `user_id` adında bir key yok, bu kod nasıl çalışıyor ulan??

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +  const wantedcontent = await models.wanted_contents.findOne({
tüm değişken isimleri **camelCase** olmalı.Dokümanı tekrar et

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +      id: user_id,
neden `wanted_contets.id` ile `user_id`'yi karşılaştırıyorsun? `user_id` ile `user_id`'yi karşılaştırmak varken.

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +    wantedcontent.destroy();
`await` ile işlemin bitmesini beklemelisin.

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +      models.content_reviews.destroy({
Konumuzun `content_reviews` ile ne alakası var?? Neden sayfamızda kullanmadıüımız kodlar duruyor.

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +      id:user_id,
`wanted_contets.id` ile `users.id` karşılaştırması yapmak sadece kodun tesadüf ile çalışmasını sağlar.Eğer sahipliğini kontrol etmek istiyorsan doğrudan `user_id` ile kontrol yapmalısın

2021-06-29 09:20 UTC, saracalihan commented on src/routes/wanted_contents/index.js
> +  } else {
Yukarıda if içinde `wantedContet` var mı diye kontrol etmektense yok mu diye kontrol edip kullanıcıya uyarı gönderip koddan çıkabilirsin.Eğer varsa kodu okumaya devam edebilir.

2021-06-30 09:29 UTC, saracalihan approved these changes

2021-06-30 09:30 UTC, merged