Message Table model  Migration  CRUD and seed
mavidurak/orientation-api pull request #34
Opened 2021-07-13 13:43 UTC by burakack

2021-07-13 18:08 UTC, saracalihan requested changes

2021-07-13 18:08 UTC, saracalihan commented on src/models/users.js
> +    models.wantedContents, {
Model ismi **snake_case** olmalı

2021-07-13 18:08 UTC, saracalihan commented on src/models/users.js
> +  models.users.hasOne(
buraya göre bir user sadece 1 mesaj atabilir, bu sistemimiziçin doğdu değil bir user'aait birden fazla mesaj bulunabilir

2021-07-13 18:08 UTC, saracalihan commented on src/models/users.js
> +  models.users.hasOne(
Aynı şekilde bir user'a birden fazla yerden mesaj da gelebilir

2021-07-13 18:08 UTC, saracalihan commented on src/routes/messages/index.js
> +      id: req.params,
`req.params` bir object. Object ile Number'ı eşitleyemezsin.

2021-07-13 18:10 UTC, burakack commented on src/models/users.js
> +    models.wantedContents, {
yanlışlıkla değiştirmiştim geri aldım

2021-08-03 07:05 UTC, saracalihan requested changes

2021-08-03 07:05 UTC, saracalihan commented on src/models/messages.js
> +    id: {
id'yi burada bir daha yazmana gerek yok

2021-08-03 07:05 UTC, saracalihan commented on src/routes/messages/index.js
> +export default [{
Tek route kullandığımız yerlerde `[ ]` kullanılmasına gerek yok doğradan `{ }` içinde yazabilirsin

2021-08-06 15:41 UTC, saracalihan requested changes

2021-08-06 15:41 UTC, saracalihan commented on src/models/users.js
`hasMany` fonksiyonunun ve içindeki objenin parantezi açılmış ama kapatılmamış

2021-08-08 18:01 UTC, merged